//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppij_web_aplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokacija
    {
        public int Id { get; set; }
        public int ID_instruktor { get; set; }
        public Nullable<double> Geo_sirina { get; set; }
        public Nullable<double> Geo_duzina { get; set; }
        public string opis { get; set; }
    
        public virtual Osoba Osoba { get; set; }
    }
}
