//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppij_web_aplikacija
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ppij_databaseEntities : DbContext
    {
        public ppij_databaseEntities()
            : base("name=ppij_databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dogovor_termin> dogovor_termin { get; set; }
        public virtual DbSet<Kategorija> Kategorija { get; set; }
        public virtual DbSet<Osoba> Osoba { get; set; }
        public virtual DbSet<Termin> Termin { get; set; }
        public virtual DbSet<osoba_predmet> osoba_predmet { get; set; }
        public virtual DbSet<Predmet> Predmet { get; set; }
        public virtual DbSet<Ustanova> Ustanova { get; set; }
    }
}
