//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppij_web_aplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termin()
        {
            this.Osoba = new HashSet<Osoba>();
            this.dogovor_termin = new HashSet<dogovor_termin>();
        }
    
        public int ID_termin { get; set; }
        public Nullable<int> dan_termin { get; set; }
        public Nullable<int> period_termin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Osoba> Osoba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dogovor_termin> dogovor_termin { get; set; }
    }
}
